### PR TITLE
Update PathFinder.h

### PR DESCRIPTION
**Pull request by PhilCMillerMTU16**
Fixed issues with Cmake compatibility issues.

### CODE REVIEW

**Comment by Sahnvour** [comment]
What does that has to do with Cmake ? You may be using an outdated compiler.

**Comment by PhilCMillerMTU16** [comment]
I actually have a mitake in that commit. It should be class, not typename.
Without class, the complier assumes its a static variable and mucks up
everything.

**Comment by Sahnvour** [comment]
You're still probably using an old compiler, what is it ?
And what about changing the use of `std::rbegin` and `std::rend` to member functions ?

**Comment by PhilCMillerMTU16** [comment]
This is a new system. All software is up-to-date.

rbegin and rend were used improperly.
http://www.cplusplus.com/reference/vector/vector/rbegin/

On Sun, Nov 15, 2015 at 3:37 PM, Sahnvour notifications@github.com wrote:

> You're still probably using an old compiler, what is it ?
> And what about changing the use of std::rbegin and std::rend to member
> functions ?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Sahnvour/PathFinder/pull/1#issuecomment-156851435.

## 

_Phillip Miller_
Electrical Engineering Undergraduate
Michigan Technological University
Blue Marble Security Enterprise
Autonomous Vehicle Project Manager
phmiller@mtu.edu - (906) 231-5817

**Comment by nm17** [comment]
@Sahnvour You can close this now.

**Comment by Sahnvour** [comment]
Good catch.

**Pull request closed without merging**
